services:
  postgres:
    image: postgres:15-alpine  # Burayı değiştirdik (veya postgres:16-alpine)
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      #- pgdata:/var/lib/postgresql/data
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      #- mongodata:/data/db
      - /data/db
#volumes:
# pgdata:
 # mongodata: